#!/bin/sh
# TO NEVER COAUTHOR WORK AGAIN!
# Rewrite HEAD if the latest message has an agent co-author trailer.
# Usage: strip-head.sh [repo-path]
set -e
repo="${1:-.}"
cd "$repo"
msg=$(git log -1 --format=%B)
case "$msg" in
  *Co-authored-by:*|*Signed-off-by: Cursor*)
    ;;
  *)
    echo "HEAD has no co-author trailer"
    exit 0
    ;;
esac
tree=$(git rev-parse 'HEAD^{tree}')
parent=$(git rev-parse 'HEAD^')
author_name=$(git log -1 --format=%an)
author_email=$(git log -1 --format=%ae)
author_date=$(git log -1 --format=%aD)
msgfile=$(mktemp)
git log -1 --format=%B | grep -v -E '^(Co-authored-by:|Signed-off-by:[[:space:]]*Cursor)' \
  | grep -v -E '^(Generated by|Assisted by)[[:space:]]+(Cursor|Claude|Grok)' \
  | python3 -c 'import sys; t=sys.stdin.read().rstrip()+"\n"; print(t, end="")' > "$msgfile"
new=$(GIT_AUTHOR_NAME="$author_name" GIT_AUTHOR_EMAIL="$author_email" GIT_AUTHOR_DATE="$author_date" \
  git commit-tree "$tree" -p "$parent" -F "$msgfile")
rm -f "$msgfile"
git reset --hard "$new"
echo "rewrote HEAD to $new (no co-author)"
git log -1 --format=%B
